# Scale Test: ~5000 pods MoE Training variant
# Single PodClique with 5000 expert worker replicas
---
apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: scale-test-5000-moe
  labels:
    app: scale-test-5000-moe
    workload-type: moe-training
spec:
  replicas: 2500
  template:
    cliques:
      - name: expert-worker
        labels:
          kai.scheduler/queue: default
        spec:
          roleName: expert-worker
          replicas: 2
          minAvailable: 2
          podSpec:
            schedulerName: kai-scheduler
            tolerations:
              - key: fake-node
                operator: Equal
                value: "true"
                effect: NoSchedule
            containers:
              - name: expert-worker
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
                    cpu: 100m
