# Scale Test: ~5000 pods (625 prefill + 624 decode ScalingGroups + 3 frontend)
# Large scale test for validating extreme-scale behavior on KWOK cluster
---
apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: scale-test-5000
  labels:
    app: scale-test-5000
spec:
  replicas: 1
  template:
    podCliqueScalingGroups:
      - name: prefill
        replicas: 625
        minAvailable: 625
        cliqueNames:
          - pleader
          - pworker
      - name: decode
        replicas: 625
        minAvailable: 625
        cliqueNames:
          - dleader
          - dworker
    cliques:
      - name: frontend
        labels:
          kai.scheduler/queue: default
        spec:
          roleName: frontend
          replicas: 3
          minAvailable: 3
          podSpec:
            schedulerName: kai-scheduler
            nodeSelector:
              type: kwok
            tolerations:
              - key: fake-node
                operator: Equal
                value: "true"
                effect: NoSchedule
            containers:
              - name: frontend
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
                    cpu: 100m
      - name: pleader
        labels:
          kai.scheduler/queue: default
        spec:
          roleName: pleader
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: kai-scheduler
            nodeSelector:
              type: kwok
            tolerations:
              - key: fake-node
                operator: Equal
                value: "true"
                effect: NoSchedule
            containers:
              - name: pleader
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
                    cpu: 100m
      - name: pworker
        labels:
          kai.scheduler/queue: default
        spec:
          roleName: pworker
          replicas: 3
          minAvailable: 3
          podSpec:
            schedulerName: kai-scheduler
            nodeSelector:
              type: kwok
            tolerations:
              - key: fake-node
                operator: Equal
                value: "true"
                effect: NoSchedule
            containers:
              - name: pworker
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
                    cpu: 100m
      - name: dleader
        labels:
          kai.scheduler/queue: default
        spec:
          roleName: dleader
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: kai-scheduler
            nodeSelector:
              type: kwok
            tolerations:
              - key: fake-node
                operator: Equal
                value: "true"
                effect: NoSchedule
            containers:
              - name: dleader
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
                    cpu: 100m
      - name: dworker
        labels:
          kai.scheduler/queue: default
        spec:
          roleName: dworker
          replicas: 3
          minAvailable: 3
          podSpec:
            schedulerName: kai-scheduler
            nodeSelector:
              type: kwok
            tolerations:
              - key: fake-node
                operator: Equal
                value: "true"
                effect: NoSchedule
            containers:
              - name: dworker
                image: registry:5001/nginx:alpine-slim
                resources:
                  requests:
                    memory: 30Mi
                    cpu: 100m
