// Copyright 2026 The Grove Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package podtemplatehash

import (
	"encoding/json"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	corev1 "k8s.io/api/core/v1"

	_ "embed"
)

//go:embed testdata/legacy-templates.json
var legacyTemplatesJSON []byte

func TestLegacyHashesMatchReleasedOperators(t *testing.T) {
	templates := legacyTemplates(t)
	// Generated from the same JSON inputs in separate modules linked against
	// k8s.io/{api,apimachinery} v0.35.5 and v0.34.3. These are persisted migration
	// identities, not expected outputs generated by the compatibility code.
	for i, hashes := range [][]string{
		{"77d6bf59f65f6ff6568", "77f57bf7dbf6f85887f"},
		{"cb4d679bc7c7d59d8bd", "b64c8bfbc66c89b7ff8"},
	} {
		assert.Equal(t, hashes, LegacyHashes(templates[i]))
	}
	assert.Equal(t, []string{"5c956bfb7c9dc87bb4bc", "5b55bbd99844d8fb84b8"}, LegacyHashes(templates...))
}

func TestLegacyHashesRejectUnsupportedFields(t *testing.T) {
	for _, tt := range []struct {
		name   string
		mutate func([]*corev1.PodTemplateSpec)
	}{
		{name: "workload reference", mutate: func(templates []*corev1.PodTemplateSpec) {
			templates[0].Spec.WorkloadRef = &corev1.WorkloadReference{Name: "workload", PodGroup: "group"}
		}},
		{name: "certificate annotations", mutate: func(templates []*corev1.PodTemplateSpec) {
			templates[1].Spec.Volumes[0].Projected.Sources[0].PodCertificate.UserAnnotations = map[string]string{"example.com/identity": "worker"}
		}},
		{name: "explicit empty certificate annotations", mutate: func(templates []*corev1.PodTemplateSpec) {
			templates[1].Spec.Volumes[0].Projected.Sources[0].PodCertificate.UserAnnotations = map[string]string{}
		}},
	} {
		t.Run(tt.name, func(t *testing.T) {
			templates := legacyTemplates(t)
			original := LegacyHashes(templates...)
			require.Len(t, original, 2)
			tt.mutate(templates)
			changed := LegacyHashes(templates...)
			require.Len(t, changed, 1)
			assert.NotEqual(t, original[0], changed[0])
			assert.NotContains(t, changed, original[1])
		})
	}
}

func TestLegacyHashesPreserveOrderedInputs(t *testing.T) {
	templates := legacyTemplates(t)
	original := LegacyHashes(templates...)
	reordered := LegacyHashes(templates[1], templates[0])
	require.Len(t, reordered, len(original))
	for i := range original {
		assert.NotEqual(t, original[i], reordered[i])
	}
	templates[1].Spec.Containers[0].Env[0], templates[1].Spec.Containers[0].Env[1] =
		templates[1].Spec.Containers[0].Env[1], templates[1].Spec.Containers[0].Env[0]
	for i, changed := range LegacyHashes(templates...) {
		assert.NotEqual(t, original[i], changed)
	}
}

func legacyTemplates(t *testing.T) []*corev1.PodTemplateSpec {
	t.Helper()
	var templates []*corev1.PodTemplateSpec
	require.NoError(t, json.Unmarshal(legacyTemplatesJSON, &templates))
	return templates
}
